#!/bin/bash
if [[ $(realpath $0) =~ ^(.*)/([^/]+)$ ]]; then
        WORKDIR=${BASH_REMATCH[1]}
fi
JQDIR=${WORKDIR}/tpl
source ${WORKDIR}/mod.command

# detect available cmds
commands() {
	#echo -e '\0033\0143'
	#bind "set completion-display-width 0"
	#bind "set history-preserve-point on"
	#bind "set show-all-if-ambiguous on"
	#bind "set show-all-if-unmodified on"
	#bind "set colored-completion-prefix on"
	#bind "set colored-stats on"
	#bind "set page-completions off"
	#bind "set completion-query-items 0"
	#bind "set skip-completed-text on"
	printf "%s\n" "<cmd>"
	for FILE in ${WORKDIR}/cmd.*.sh; do
		if [[ $FILE =~ cmd[.](.+)[.]sh ]]; then
			printf "%s\n" "${BASH_REMATCH[1]}"
		fi
	done
	#bind -v | grep page
	bind -x '"\C-r"':reset;
	exit 1
}

writejq() {
	printf "%s\n" "<cmd>"
	for FILE in ${JQDIR}/tpl.*.jq; do
		if [[ $FILE =~ tpl[.](.+)[.]jq ]]; then
			printf "%s\n" "${BASH_REMATCH[1]}"
		fi
	done
	exit 1
}

# switch
if [[ -n "$1" ]]; then
	case "${1}" in
		list)
			commands
		;;
		write)
			writejq
		;;
		*)
			if [ -f "${WORKDIR}/cmd.${1}.sh" ]; then
				eval "${WORKDIR}/cmd.${1}.sh ${@:2}"
			fi
		;;
	esac
fi
