#!/bin/bash
if [[ $(realpath $0) =~ ^(.*)/([^/]+)$ ]]; then
        WORKDIR=${BASH_REMATCH[1]}
fi
JQDIR=${WORKDIR}/tpl
source ${WORKDIR}/mod.command

# detect available cmds
commands() {
	printf "%s\n" "list"
	for FILE in ${WORKDIR}/cmd.*.sh; do
		if [[ $FILE =~ cmd[.](.+)[.]sh ]]; then
			printf "%s\n" "${BASH_REMATCH[1]}"
		fi
	done
	exit 1
}

# switch
if [[ -n "$1" ]]; then
	case "${1}" in
		list)
			commands
		;;
		*)
			if [ -f "${WORKDIR}/cmd.${1}.sh" ]; then
				eval "${WORKDIR}/cmd.${1}.sh ${@:2}"
			fi
		;;
	esac
fi
